language: python
python:
        - "3.5.2"
env:
  global:
    - CC_TEST_REPORTER_ID=$TEST_REPORTER_ID
services:
    - postgresql
before_script:
        - psql -c 'create database testdb;' -U postgres
        - psql -c "create user jp with password 'cavier';" -U postgres
        - flask db create-all
install:
        - pip install flask
        - pip install pytest
        - pip install pytest-cov
        - pip install flask_restful
        - pip install coveralls
        - pip install codecov
        - pip install python-dotenv
        - pip install psycopg2-binary
        - pip install flask_jwt_extended
        - pip install flask-mail
script:
        - pytest --cov=./app/tests/v2
after_success:
        - codecov
        - coveralls
        - codeclimate-test-reporter
