language: python
python:
        - "3.5.2"
env:
  global:
    - CC_TEST_REPORTER_ID=$TEST_REPORTER_ID
services:
    - postgresql
before_script:
        - psql -c 'create database testdb;' -U postgres
        - psql -c "create user jp with password 'cavier';" -U postgres
install:
        - pip install -r requirements.txt
script:
        - pytest
after_success:
        - coveralls
        - codeclimate-test-reporter
